use sakila;

-- 1 List the number of films per category.
select * from sakila.film_category;

select category_id, count(film_id) as CantidadPelis
from film_category
group by category_id;

-- 2 Retrieve the store ID, city, and country for each store.

select * from sakila.city;

select a.store_id, c.city, d.country from sakila.store AS a
join address AS b
on a.address_id = b.address_id
join city as c
on b.city_id = c.city_id
join country as d
on d.country_id = c.country_id;

-- 3 Calculate the total revenue generated by each store in dollars.
select * from sakila.staff;

SELECT s.STORE_ID, SUM(AMOUNT)
FROM STORE s
LEFT JOIN STAFF f
ON s.store_id = f.store_id
LEFT JOIN PAYMENT p
ON f.staff_id = P.staff_id
GROUP BY s.STORE_ID;

-- 4 Determine the average running time of films for each category.
select * from sakila.film;

select a.category_id, avg(c.length) as duracion_pelis from sakila.category as a
join film_category as b
on a.category_id = b.category_id
join film as c
on b.film_id = c.film_id
group by a.category_id;

-- 5 Identify the film categories with the longest average running time.

select a.category_id, avg(c.length) as duracion_pelis from sakila.category as a
join film_category as b
on a.category_id = b.category_id
join film as c
on b.film_id = c.film_id
group by a.category_id
order by duracion_pelis desc
limit 5;

-- 6 Display the top 10 most frequently rented movies in descending order.
select * from sakila.rental;

select distinct a.rental_id, c.title as duracion from sakila.rental as a
join inventory as b
on a.inventory_id = b.inventory_id
join film as c
on b.film_id = c.film_id
group by c.title
order by duracion asc
limit 10;
